pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'python3 jenkins/test_with_tdd/source/team.py'
            }
        }
        stage('Test') {
            steps {
                sh 'python3 -m unittest discover jenkins/test_with_tdd/tests'
            }

           }
        stage('Copy Build') {
            steps {
                sh 'echo "Hello World"'
            }
            
            
        }
    }
}