pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'python3 jenkins/source/pyexample.py'
            }
        }
        stage('Test') {
            steps {
                sh 'python3 jenkins/source/test.py'
            }

           }
        stage('Copy Build') {
            steps {
                sh 'mkdir /var/lib/jenkins/jobs/buildCopy'
                sh 'cp -r /var/lib/jenkins/jobs/test/* /var/lib/jenkins/jobs/buildCopy'
            }
            
            
        }
    }
}